### PR TITLE
Update biosimulators.json

### PR DESCRIPTION
**Pull request by vcellmike**
test committ

### CODE REVIEW

**Review by gmarupilla — APPROVED** [review]
I'll remove comments once you're done

**Comment by bilalshaikh42** [comment]
@gmarupilla Should this be merged in?

**Comment by gmarupilla** [comment]
> @gmarupilla Should this be merged in?

I'm expecting more changes to KISAO IDs and `modeling frameworks ` and `model formats,` but these changes are independent. So, we can merge.

**Comment by gmarupilla** [comment]
I'll resolve the conflicts and merge to dev branch

**Comment by bilalshaikh42** [comment]
If there are more changes soon, then we can wait

**Pull request closed without merging**
